/**
 * Antenny API
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Endpoint from './Endpoint';
import Resource from './Resource';

/**
 * The NewSubscription model module.
 * @module model/NewSubscription
 * @version 1.0.0
 */
class NewSubscription {
    /**
     * Constructs a new <code>NewSubscription</code>.
     * @alias module:model/NewSubscription
     */
    constructor() { 
        
        NewSubscription.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NewSubscription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewSubscription} obj Optional instance to populate.
     * @return {module:model/NewSubscription} The populated <code>NewSubscription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewSubscription();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('resource')) {
                obj['resource'] = Resource.constructFromObject(data['resource']);
            }
            if (data.hasOwnProperty('endpoint')) {
                obj['endpoint'] = Endpoint.constructFromObject(data['endpoint']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
NewSubscription.prototype['name'] = undefined;

/**
 * @member {module:model/Resource} resource
 */
NewSubscription.prototype['resource'] = undefined;

/**
 * @member {module:model/Endpoint} endpoint
 */
NewSubscription.prototype['endpoint'] = undefined;






export default NewSubscription;

