/**
 * Antenny API
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Registration model module.
 * @module model/Registration
 * @version 1.1.0
 */
class Registration {
    /**
     * Constructs a new <code>Registration</code>.
     * @alias module:model/Registration
     */
    constructor() { 
        
        Registration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Registration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Registration} obj Optional instance to populate.
     * @return {module:model/Registration} The populated <code>Registration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Registration();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('customerId')) {
                obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('clients')) {
                obj['clients'] = ApiClient.convertToType(data['clients'], ['String']);
            }
            if (data.hasOwnProperty('subscriptions')) {
                obj['subscriptions'] = ApiClient.convertToType(data['subscriptions'], ['String']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Registration.prototype['id'] = undefined;

/**
 * @member {String} customerId
 */
Registration.prototype['customerId'] = undefined;

/**
 * @member {String} secret
 */
Registration.prototype['secret'] = undefined;

/**
 * @member {String} status
 */
Registration.prototype['status'] = undefined;

/**
 * @member {Array.<String>} clients
 */
Registration.prototype['clients'] = undefined;

/**
 * @member {Array.<String>} subscriptions
 */
Registration.prototype['subscriptions'] = undefined;

/**
 * @member {Date} created
 */
Registration.prototype['created'] = undefined;

/**
 * @member {Date} modified
 */
Registration.prototype['modified'] = undefined;






export default Registration;

