/**
 * Antenny API
 * This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@antenny.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Subscription from './Subscription';

/**
 * The SubscriptionList model module.
 * @module model/SubscriptionList
 * @version 1.0.0
 */
class SubscriptionList {
    /**
     * Constructs a new <code>SubscriptionList</code>.
     * @alias module:model/SubscriptionList
     */
    constructor() { 
        
        SubscriptionList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubscriptionList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionList} obj Optional instance to populate.
     * @return {module:model/SubscriptionList} The populated <code>SubscriptionList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionList();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Subscription]);
            }
            if (data.hasOwnProperty('lastKey')) {
                obj['lastKey'] = ApiClient.convertToType(data['lastKey'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Subscription>} items
 */
SubscriptionList.prototype['items'] = undefined;

/**
 * @member {String} lastKey
 */
SubscriptionList.prototype['lastKey'] = undefined;






export default SubscriptionList;

